name: assimp
version: 0.0.6+1
description: >-
  Open Asset Import Library aka Assimp for Dart. Assimp can import various
  well-known 3D model formats in a uniform manner.
homepage: https://github.com/jpnurmi/assimp.dart
repository: https://github.com/jpnurmi/assimp.dart
issue_tracker: https://github.com/jpnurmi/assimp.dart/issues

environment:
  sdk: '>=2.14.0-0 <3.0.0'

dependencies:
  dylib: ^0.3.2+1
  equatable: ^2.0.0
  ffi: ^1.0.0
  meta: ^1.3.0
  quiver: ^3.0.0
  vector_math: ^2.1.0

dev_dependencies:
  ffigen: ^2.4.1
  path: ^1.8.0
  test: ^1.17.3
  test_cov: ^1.0.1
